version: "3.9"

services:
  web:
    build: .
    container_name: blind-chess
    depends_on:
      - redis
    ports:
      - ${PORT}:${PORT}
    environment:
      - PORT=${PORT}
      - REDISHOST=redisdb
  redisdb:
    image: redis:alpine
    container_name: blind-chess-db
    ports:
      - 6379:6379